# Generated by Django 5.1.1 on 2024-09-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fosters',
            fields=[
                ('fosterID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fosterName', models.CharField(max_length=50)),
                ('fosterEmail', models.EmailField(max_length=70)),
                ('fosterPhone', models.CharField(max_length=10)),
                ('fosterStreet', models.CharField(max_length=50)),
                ('fosterCity', models.CharField(max_length=50)),
                ('fosterState', models.CharField(max_length=2)),
                ('fotserZip', models.CharField(max_length=5)),
            ],
        ),
    ]
