# Generated by Django 5.1.1 on 2024-09-23 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fosters',
            new_name='Foster',
        ),
    ]
