# Generated by Django 5.1.1 on 2024-09-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_rename_fosters_foster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foster',
            old_name='fotserZip',
            new_name='fosterZip',
        ),
    ]
